### PR TITLE
Player 2548

### PR DESCRIPTION
**Pull request by aldigun**

### CODE REVIEW

**Comment by aldigun** [comment]
DO NOT MERGE yet. Until player-v4 general deployment script is completed.

**Comment by pilievOoyala** [comment]
LGTM

**Comment by aldigun** [comment]
Since https://git.corp.ooyala.com/projects/PBW/repos/player-v4/pull-requests/27/overview was merged and verified on both sandbox and candidate, we need this to be merged.

**Comment by aldigun** [comment]
I will merge this commit as we have enough approvals. Deployment build needs this update.

**Pull request merged**
